services:
  gateway:
    image: university-gateway:prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080
      APPLICATION_NAME: GatewayService
      EUREKA_HOSTNAME: eureka-prod
      EUREKA_DEFAULTZONE: https://eureka.university-academic-tracker.com/eureka/
      JAVA_OPTS: "-Xms256m -Xmx512m"
    restart: always
